--- #YAML:1.0
name:                WWW-Salesforce
version:             0.10
abstract:            this class provides a simple abstraction layer between SOAP::Lite and Salesforce.com.
license:             perl
author:              
    - Chase Whitener <cwhitener@gmail.com>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Crypt::SSLeay:                 0.56
    SOAP::Lite:                    0.68
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
